def buildReferenceArrays():
    commonTCPPortAssignments = [
        #[port num, description]
        [5, "Remote job entry"],
        [7, "Echo Protocol"],
        [9, "Discard Protocol"],
        [11, "Active Users (systat service)"],
        [13, "Daytime Protocol"],
        [15, "Previously netstat service"],
        [17, "Quote of the Day (QOTD)"],
        [18, "Message Send Protocol"],
        [19, "Character Generator Protocol (CHARGEN)"],
        [20, "File Transfer Protocol (FTP) data transfer"],
        [21, "File Transfer Protocol (FTP) control (command)"],
        [22, "Secure Shell (SSH)"],
        [23, "Telnet protocol - unencrypted text communications"],
        [25, "Simple Mail Transfer Protocol (SMTP)"],
        [37, "Time Protocol"],
        [38, "Route Access Protocol (RAP)"],
        [39, "Resource Location Protocol (RLP)"],
        [42, "Host Name Server Protocol"],
        [43, "WHOIS protocol"],
        [49, "TACACS+ Login Host protocol"],
        [50, "Remote Mail Checking Protocol"],
        [51, "Previously Interface Message Processor logical address management"],
        [52, "Xerox Network Systems (XNS) Time Protocol"],
        [53, "Domain Name System (DNS)"],
        [54, "Xerox Network Systems (XNS) clearinghouse"],
        [56, "Xerox Network Systems (XNS) authentication"],
        [57, "Any private terminal access"],
        [58, "Xerox Network Systems (XNS) Mail"],
        [70, "Gopher protocol"],
        [71, "NETRJS protocol"],
        [72, "NETRJS protocol"],
        [73, "NETRJS protocol"],
        [74, "NETRJS protocol"],
        [75, "Any private dial out service"],
        [77, "Any private Remote job entry"],
        [79, "Finger protocol"],
        [80, "Hypertext Transfer Protocol (HTTP)"],
        [81, "TorPark onion routing"],
        [88, "Kerberos"],
        [90, "dnsix (DoD Network Security for Information Exchange) Securit "],
        [90, "PointCast (dotcom)"],
        [99, "WIP message protocol"],
        [101, "NIC host name"],
        [102, "ISO Transport Service Access Point (TSAP) Class 0 protocol"],
        [104, "Digital Imaging and Communications in Medicine (DICOM"],
        [105, "CCSO Nameserver"],
        [107, "Remote User Telnet Service (RTelnet)"],
        [108, "IBM Systems Network Architecture (SNA) gateway access server"],
        [109, "Post Office Protocol"],
        [110, "Post Office Protocol"],
        [111, "Open Network Computing Remote Procedure Call (ONC RPC"],
        [113, "Ident"],
        [113, "Authentication Service (auth)"],
        [115, "Simple File Transfer Protocol"],
        [117, "UUCP Mapping Project (path service)"],
        [118, "Structured Query Language (SQL) Services"],
        [119, "Network News Transfer Protocol (NNTP)"],
        [126, "Formerly Unisys Unitary Login"],
        [135, "DCE endpoint resolution / Microsoft EPMAP (End Point Mapper)"],
        [138, "NetBIOS Datagram Service"],
        [139, "NetBIOS Session Service"],
        [143, "Internet Message Access Protocol (IMAP)"],
        [152, "Background File Transfer Program (BFTP)"],
        [153, "Simple Gateway Monitoring Protocol (SGMP)"],
        [156, "Structured Query Language (SQL) Service"],
        [158, "Distributed Mail System Protocol (DMSP"],
        [162, "Simple Network Management Protocol Trap (SNMPTRAP)"],
        [170, "Print server"],
        [177, "X Display Manager Control Protocol (XDMCP)"],
        [179, "Border Gateway Protocol (BGP)"],
        [194, "Internet Relay Chat (IRC)"],
        [199, "SNMP multiplexing protocol (SMUX)"],
        [201, "AppleTalk Routing Maintenance"],
        [209, "Quick Mail Transfer Protocol"],
        [210, "ANSI Z39.50"],
        [213, "Internetwork Packet Exchange (IPX)"],
        [218, "Message posting protocol (MPP)"],
        [220, "Internet Message Access Protocol (IMAP)"],
        [259, "Efficient Short Remote Operations (ESRO)"],
        [262, "Arcisdms"],
        [264, "Border Gateway Multicast Protocol (BGMP)"],
        [280, "http-mgmt"],
        [300, "ThinLinc Web Access"],
        [308, "Novastor Online Backup"],
        [311, "Mac OS X Server Admin"],
        [318, "PKIX Time Stamp Protocol (TSP)"],
        [350, "Mapping of Airline Traffic over Internet Protocol (MATIP) type A"],
        [351, "MATIP type B"],
        [356, "cloanto-net-1 (used by Cloanto Amiga Explorer and VMs)"],
        [366, "On-Demand Mail Relay (ODMR)"],
        [369, "Rpc2portmap"],
        [370, "codaauth2"],
        [371, "ClearCase albd"],
        [383, "HP data alarm manager"],
        [384, "A Remote Network Server System"],
        [387, "AURP (AppleTalk Update-based Routing Protocol)"],
        [389, "Lightweight Directory Access Protocol (LDAP)"],
        [399, "Digital Equipment Corporation DECnet (Phase V+) over TCP/IP"],
        [401, "Uninterruptible power supply (UPS)"],
        [427, "Service Location Protocol (SLP)"],
        [433, "NNSP"],
        [434, "Mobile IP Agent (RFC 5944)"],
        [443, "Hypertext Transfer Protocol over TLS/SSL (HTTPS)"],
        [444, "Simple Network Paging Protocol (SNPP)"],
        [444, "Well known Slither.io port"],
        [445, "Microsoft-DS Active Directory"],
        [445, "Microsoft-DS SMB"],
        [464, "Kerberos Change/Set password"],
        [465, "URL Rendezvous Directory for SSM (Cisco protocol)"],
        [465, "Authenticated SMTP"],
        [475, "tcpnethaspsrv"],
        [491, "GO-Global remote access and application publishing software"],
        [497, "Retrospect"],
        [502, "Modbus Protocol"],
        [504, "Citadel"],
        [510, "FirstClass Protocol (FCP)"],
        [512, "Rexec"],
        [513, "rlogin"],
        [514, "Remote Shell"],
        [515, "Line Printer Daemon (LPD)"],
        [520, "efs"],
        [524, "NetWare Core Protocol (NCP)"],
        [530, "Remote procedure call (RPC)"],
        [531, "AOL Instant Messenger"],
        [532, "netnews"],
        [540, "Unix-to-Unix Copy Protocol (UUCP)"],
        [542, "commerce (Commerce Applications)"],
        [543, "klogin"],
        [544, "kshell"],
        [546, "DHCPv6 client"],
        [547, "DHCPv6 server"],
        [548, "Apple Filing Protocol (AFP) over TCP"],
        [550, "new-rwho"],
        [554, "Real Time Streaming Protocol (RTSP)"],
        [556, "Remotefs"],
        [563, "NNTP over TLS/SSL (NNTPS)"],
        [564, "9P (Plan 9)"],
        [585, "Legacy use of Internet Message Access Protocol over TLS/SSL (IMAPS)"],
        [587, "email message submission"],
        [591, "FileMaker 6.0 (and later) Web Sharing (HTTP Alternate"],
        [593, "HTTP RPC Ep Map"],
        [601, "Reliable Syslog Service - used for system logging"],
        [604, "TUNNEL profile"],
        [625, "Open Directory Proxy (ODProxy)"],
        [631, "Internet Printing Protocol (IPP)"],
        [631, "Common Unix Printing System (CUPS) administration console (extension to IPP)"],
        [635, "RLZ DBase"],
        [636, "Lightweight Directory Access Protocol over TLS/SSL (LDAPS)"],
        [639, "MSDP"],
        [641, "SupportSoft Nexus Remote Command (control/listening)"],
        [643, "SANity"],
        [646, "Label Distribution Protocol (LDP)"],
        [647, "DHCP Failover protocol"],
        [648, "Registry Registrar Protocol (RRP)"],
        [651, "IEEE-MMS"],
        [653, "SupportSoft Nexus Remote Command (data)"],
        [654, "Media Management System (MMS) Media Management Protocol (MMP)"],
        [655, "Tinc VPN daemon"],
        [657, "IBM RMC (Remote monitoring and Control) protocol"],
        [660, "Mac OS X Server administration"],
        [666, "Doom"],
        [666, "airserv-ng"],
        [674, "Application Configuration Access Protocol (ACAP)"],
        [688, "REALM-RUSD (ApplianceWare Server Appliance Management Protocol)"],
        [690, "Velneo Application Transfer Protocol (VATP)"],
        [691, "MS Exchange Routing"],
        [694, "Linux-HA high-availability heartbeat"],
        [695, "IEEE Media Management System over SSL (IEEE-MMS-SSL)"],
        [700, "Extensible Provisioning Protocol (EPP)"],
        [701, "Link Management Protocol (LMP)"],
        [702, "IRIS"],
        [706, "Secure Internet Live Conferencing (SILC)"],
        [711, "Cisco Tag Distribution Protocol"],
        [712, "Topology Broadcast based on Reverse-Path Forwarding routing protocol (TBRPF"],
        [749, "Kerberos (protocol) administration"],
        [751, "kerberos_master"],
        [753, "Reverse Routing Header (RRH)"],
        [754, "tell send"],
        [754, "krb5_prop"],
        [760, "krbupdate "],
        [782, "Conserver serial-console management server"],
        [783, "SpamAssassin spamd daemon"],
        [800, "mdbs-daemon"],
        [808, "Microsoft Net.TCP Port Sharing Service"],
        [829, "Certificate Management Protocol"],
        [830, "NETCONF over SSH"],
        [831, "NETCONF over BEEP"],
        [832, "NETCONF for SOAP over HTTPS"],
        [833, "NETCONF for SOAP over BEEP"],
        [843, "Adobe Flash"],
        [847, "DHCP Failover protocol"],
        [848, "Group Domain Of Interpretation (GDOI) protocol"],
        [853, "DNS over TLS (RFC 7858)"],
        [860, "iSCSI (RFC 3720)"],
        [861, "OWAMP control (RFC 4656)"],
        [862, "TWAMP control (RFC 5357)"],
        [873, "rsync file synchronization protocol"],
        [888, "CDDBP / IBM Endpoint Manager Remote Control"],
        [897, "Brocade SMI-S RPC"],
        [898, "Brocade SMI-S RPC SSL"],
        [902, "VMware ESXi"],
        [903, "VMware ESXi"],
        [953, "BIND remote name daemon control (RNDC)"],
        [981, "Remote HTTPS management for firewall devices running embedded Check Point VPN-1 software"],
        [987, "Microsoft Remote Web Workplace"],
        [989, "FTPS Protocol (data)"],
        [990, "FTPS Protocol (control)"],
        [991, "Netnews Administration System (NAS)"],
        [992, "Telnet protocol over TLS/SSL"],
        [993, "Internet Message Access Protocol over TLS/SSL (IMAPS)"],
        [994, "Internet Relay Chat over TLS/SSL (IRCS)"],
        [995, "Post Office Protocol 3 over TLS/SSL (POP3S)"],
        [1010, "ThinLinc web-based administration interface"],
        [1058, "nim"],
        [1059, "nimreg"],
        [1080, "SOCKS proxy"],
        [1085, "WebObjects"],
        [1098, "rmiactivation"],
        [1099, "rmiregistry"],
        [1109, "Kerberos Post Office Protocol (KPOP)"],
        [1119, "Battle.net chat/game protocol"],
        [1194, "OpenVPN"],
        [1198, "The cajo project Free dynamic transparent distributed computing in Java"],
        [1214, "Kazaa"],
        [1220, "QuickTime Streaming Server administration"],
        [1234, "Infoseek search agent"],
        [1241, "Nessus Security Scanner"],
        [1270, "Microsoft System Center Operations Manager (SCOM)"],
        [1293, "Internet Protocol Security (IPSec)"],
        [1311, "Windows RxMon.exe"],
        [1311, "Dell OpenManage HTTPS"],
        [1337, "neo4j-shell"],
        [1337, "WASTE Encrypted File Sharing Program"],
        [1341, "Qubes (Manufacturing Execution System)"],
        [1344, "Internet Content Adaptation Protocol"],
        [1352, "IBM Lotus Notes/Domino (RPC) protocol"],
        [1360, "Mimer SQL"],
        [1414, "IBM WebSphere MQ (formerly known as MQSeries)"],
        [1417, "Timbuktu Service 1 Port"],
        [1418, "Timbuktu Service 2 Port"],
        [1419, "Timbuktu Service 3 Port"],
        [1420, "Timbuktu Service 4 Port"],
        [1431, "Reverse Gossip Transport Protocol (RGTP)"],
        [1433, "Microsoft SQL Server database management system (MSSQL) server"],
        [1434, "Microsoft SQL Server database management system (MSSQL) monitor"],
        [1492, "Sid Meier's CivNet"],
        [1494, "Citrix Independent Computing Architecture (ICA)"],
        [1500, "IBM Tivoli Storage Manager server"],
        [1501, "IBM Tivoli Storage Manager client scheduler"],
        [1503, "Windows Live Messenger (Whiteboard and Application Sharing)"],
        [1512, "Microsoft's Windows Internet Name Service (WINS)"],
        [1513, "Garena game client"],
        [1521, "nCUBE License Manager"],
        [1521, "Oracle database default listener"],
        [1524, "ingreslock"],
        [1527, "Oracle Net Services"],
        [1527, "Apache Derby Network Server"],
        [1533, "IBM Sametime Virtual Places Chat"],
        [1547, "Laplink"],
        [1550, "Gadu-Gadu (direct client-to-client)"],
        [1581, "MIL STD 2045-47001 VMF"],
        [1581, "IBM Tivoli Storage Manager web client"],
        [1582, "IBM Tivoli Storage Manager server web interface"],
        [1589, "Cisco VLAN Query Protocol (VQP)"],
        [1604, "DarkComet remote administration tool (RAT)"],
        [1626, "iSketch"],
        [1627, "iSketch"],
        [1628, "LonTalk normal"],
        [1629, "LonTalk urgent"],
        [1666, "Perforce"],
        [1677, "Novell GroupWise clients in client/server access mode"],
        [1688, "Microsoft Key Management Service (KMS) for Windows Activation"],
        [1701, "Layer 2 Forwarding Protocol (L2F)"],
        [1707, "Windward Studios games (vdmplay)"],
        [1719, "H.323 registration and alternate communication"],
        [1720, "H.323 call signaling"],
        [1723, "Point-to-Point Tunneling Protocol (PPTP)"],
        [1755, "Microsoft Media Services (MMS"],
        [1761, "Novell ZENworks"],
        [1801, "Microsoft Message Queuing"],
        [1812, "RADIUS authentication protocol"],
        [1813, "RADIUS accounting protocol"],
        [1863, "Microsoft Notification Protocol (MSNP)"],
        [1883, "MQTT (formerly MQ Telemetry Transport)"],
        [1935, "Macromedia Flash Communications Server MX"],
        [1935, "Real Time Messaging Protocol (RTMP)"],
        [1970, "Netop Remote Control"],
        [1972, "InterSystems Cache"],
        [1984, "Big Brother"],
        [1985, "Cisco Hot Standby Router Protocol (HSRP)"],
        [1998, "Cisco X.25 over TCP (XOT) service"],
        [2000, "Cisco Skinny Client Control Protocol (SCCP)"],
        [2033, "Civilization IV multiplayer"],
        [2056, "Civilization IV multiplayer"],
        [2080, "Autodesk NLM (FLEXlm)"],
        [2082, "cPanel default"],
        [2083, "Secure RADIUS Service (radsec)"],
        [2083, "cPanel default SSL"],
        [2086, "GNUnet"],
        [2086, "WebHost Manager default"],
        [2087, "WebHost Manager default SSL"],
        [2095, "cPanel default web mail"],
        [2096, "cPanel default SSL web mail"],
        [2100, "Warzone 2100 multiplayer"],
        [2101, "Networked Transport of RTCM via Internet Protocol (NTRIP)"],
        [2102, "Zephyr Notification Service server"],
        [2103, "Zephyr Notification Service serv-hm connection"],
        [2104, "Zephyr Notification Service hostmanager"],
        [2123, "GTP control messages (GTP-C)"],
        [2142, "TDMoIP (TDM over IP)"],
        [2152, "GTP user data messages (GTP-U)"],
        [2159, "GDB remote debug port"],
        [2181, "EForward-document transport system"],
        [2181, "Apache ZooKeeper default client port"],
        [2195, "Apple Push Notification Service"],
        [2196, "Apple Push Notification Service"],
        [2210, "NOAAPORT Broadcast Network"],
        [2211, "EMWIN"],
        [2221, "ESET anti-virus updates"],
        [2222, "EtherNet/IP implicit messaging for IO data / ESET Remote administrator"],
        [2223, "ESET Remote administrator"],
        [2224, "ESET Remote administrator"],
        [2225, "ESET Remote administrator"],
        [2226, "ESET Remote administrator"],
        [2261, "CoMotion master"],
        [2262, "CoMotion backup"],
        [2266, "M-Files"],
        [2351, "AIM game LAN network port"],
        [2368, "Ghost (blogging platform)"],
        [2369, "Default for BMC Control-M/Server Configuration Agent"],
        [2370, "Default for BMC Control-M/Server"],
        [2375, "Docker REST API (plain)"],
        [2376, "Docker REST API (SSL)"],
        [2379, "CoreOS etcd client communication"],
        [2379, "KGS Go Server"],
        [2380, "CoreOS etcd server communication"],
        [2399, "FileMaker Data Access Layer (ODBC/JDBC)"],
        [2401, "CVS version control system password-based server"],
        [2404, "IEC 60870-5-104"],
        [2424, "OrientDB database listening for binary client connections"],
        [2427, "Media Gateway Control Protocol (MGCP) media gateway"],
        [2447, "ovwdb-OpenView Network Node Manager (NNM) daemon"],
        [2480, "OrientDB database listening for HTTP client connections"],
        [2483, "Oracle database listening for insecure client connections to the listener"],
        [2484, "Oracle database listening for SSL client connections to the listener"],
        [2541, "LonTalk/IP"],
        [2546, "EVault data protection services"],
        [2547, "EVault data protection services"],
        [2548, "EVault data protection services"],
        [2593, "Ultima Online servers"],
        [2598, "Citrix Independent Computing Architecture (ICA) with Session Reliability"],
        [2599, "Ultima Online servers"],
        [2638, "SQL Anywhere database server"],
        [2727, "Media Gateway Control Protocol (MGCP) media gateway controller (call agent)"],
        [2809, "corbaloc:iiop URL"],
        [2811, "gsi ftp"],
        [2827, "I2P BOB Bridge"],
        [2944, "Megaco text H.248"],
        [2945, "Megaco binary (ASN.1) H.248"],
        [2947, "gpsd"],
        [2948, "WAP push Multimedia Messaging Service (MMS)"],
        [2949, "WAP push secure (MMS)"],
        [2967, "Symantec System Center agent (SSC-AGENT)"],
        [3000, "Cloud9 IDE server"],
        [3000, "Ruby on Rails development default"],
        [3000, "Meteor development default"],
        [3000, "Resilio Sync"],
        [3004, "iSync"],
        [3020, "Common Internet File System (CIFS). See also port 445 for Server Message Block (SMB)"],
        [3050, "gds-db (Interbase/Firebird databases)"],
        [3052, "APC PowerChute Network"],
        [3074, "Xbox LIVE and Games for Windows - Live"],
        [3101, "BlackBerry Enterprise Server communication protocol"],
        [3128, "Squid caching web proxy"],
        [3225, "Fibre Channel over IP (FCIP)"],
        [3233, "WhiskerControl research control protocol"],
        [3260, "iSCSI"],
        [3268, "msft-gc"],
        [3269, "msft-gc-ssl"],
        [3283, "Net Assistant"],
        [3283, "Apple Remote Desktop 2.0 or later"],
        [3305, "Odette File Transfer Protocol (OFTP)"],
        [3306, "MySQL database system"],
        [3313, "Verisys file integrity monitoring software"],
        [3316, "AzimuthVMS database port for the CCTV recording software AzimuthVMS"],
        [3323, "DECE GEODI Server"],
        [3333, "Eggdrop"],
        [3333, "Network Caller ID server"],
        [3333, "CruiseControl.rb"],
        [3386, "GTP' 3GPP GSM/UMTS CDR logging protocol"],
        [3389, "Microsoft Terminal Server (RDP) officially registered as Windows Based Terminal (WBT)"],
        [3396, "Novell NDPS Printer Agent"],
        [3412, "xmlBlaster"],
        [3455, "Resource Reservation Protocol (RSVP)"],
        [3423, "Xware xTrm Communication Protocol"],
        [3424, "Xware xTrm Communication Protocol over SSL"],
        [3478, "STUN"],
        [3478, "TURN"],
        [3478, "STUN Behavior Discovery."],
        [3479, "PlayStation Network"],
        [3480, "PlayStation Network"],
        [3483, "Slim Devices SlimProto protocol"],
        [3493, "Network UPS Tools (NUT)"],
        [3516, "Smartcard Port"],
        [3535, "SMTP alternate"],
        [3606, "Splitlock Server"],
        [3632, "Distcc"],
        [3644, "Evidian"],
        [3645, "Cyc"],
        [3659, "Apple SASL"],
        [3667, "Information Exchange"],
        [3689, "Digital Audio Access Protocol (DAAP)"],
        [3690, "Subversion (SVN)"],
        [3702, "Web Services Dynamic Discovery (WS-Discovery)"],
        [3724, "Some Blizzard games"],
        [3724, "Club Penguin Disney online game for kids"],
        [3725, "Netia NA-ER Port"],
        [3768, "RBLcheckd server daemon"],
        [3804, "Harman Professional HiQnet protocol"],
        [3825, "RedSeal Networks client/server connection"],
        [3826, "WarMUX game server"],
        [3826, "RedSeal Networks client/server connection"],
        [3835, "RedSeal Networks client/server connection"],
        [3830, "System Management Agent"],
        [3856, "ERP Server Application used by F10 Software"],
        [3880, "IGRS"],
        [3868, "Diameter base protocol (RFC 3588)"],
        [3872, "Oracle Enterprise Manager Remote Agent"],
        [3900, "udt_os"],
        [3978, "OpenTTD game (masterserver and content service)"],
        [3979, "OpenTTD game"],
        [3999, "Norman distributed scanning service"],
        [4000, "Diablo II game"],
        [4001, "Microsoft Ants game"],
        [4001, "CoreOS etcd client communication"],
        [4018, "Protocol information and warnings"],
        [4035, "IBM Rational Developer for System z Remote System Explorer Daemon"],
        [4045, "Solaris lockd NFS lock daemon/manager"],
        [4050, "Mud Master Chat protocol (MMCP) - Peer-to-peer communications between MUD clients."],
        [4089, "OpenCORE Remote Control Service"],
        [4090, "Kerio"],
        [4093, "PxPlus Client server interface ProvideX"],
        [4096, "Ascom Timeplex Bridge Relay Element (BRE)"],
        [4105, "Shofar (ShofarNexus)"],
        [4111, "Xgrid"],
        [4116, "Smartcard-TLS"],
        [4117, "WatchGuard System Manager"],
        [4125, "Microsoft Remote Web Workplace administration"],
        [4172, "Teradici PCoIP"],
        [4190, "ManageSieve"],
        [4198, "Couch Potato Android app"],
        [4201, "TinyMUD and various derivatives"],
        [4222, "NATS server default port"],
        [4226, "Aleph One"],
        [4242, "Orthanc - DICOM server"],
        [4242, "Quassel distributed IRC client"],
        [4243, "Docker implementations"],
        [4243, "CrashPlan"],
        [4244, "Viber"],
        [4303, "Simple Railroad Command Protocol (SRCP)"],
        [4307, "TrueConf Client - TrueConf Server media data exchange"],
        [4321, "Referral Whois (RWhois) Protocol"],
        [4352, "PJLink"],
        [4444, "Oracle WebCenter Content / Xvfb X server virtual frame buffer service / I2P HTTP/S proxy"],
        [4445, "I2P HTTP/S proxy"],
        [4486, "Integrated Client Message Service (ICMS)"],
        [4488, "Apple Wide Area Connectivity Service"],
        [4502, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4503, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4504, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4505, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4506, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4507, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4508, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4509, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4510, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4511, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4512, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4513, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4514, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4515, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4516, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4517, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4518, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4519, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4520, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4521, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4522, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4523, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4524, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4525, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4526, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4527, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4528, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4529, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4530, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4531, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4532, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4533, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4534, "Microsoft Silverlight connectable ports under non-elevated trust"],
        [4505, "Salt master"],
        [4506, "Salt master"],
        [4560, "default Log4j socketappender port"],
        [4567, "Sinatra default server port in development mode (HTTP)"],
        [4604, "Identity Registration Protocol"],
        [4605, "Direct End to End Secure Chat Protocol"],
        [4662, "OrbitNet Message Service"],
        [4662, "Default for older versions of eMule"],
        [4664, "Google Desktop Search"],
        [4711, "eMule optional web interface"],
        [4713, "PulseAudio sound server"],
        [4728, "Computer Associates Desktop and Server Management (DMP)/Port Multiplexer"],
        [4730, "Gearman's job server"],
        [4739, "IP Flow Information Export"],
        [4747, "Apprentice"],
        [4750, "BladeLogic Agent"],
        [4753, "SIMON (service and discovery)"],
        [4840, "OPC UA TCP Protocol for OPC Unified Architecture from OPC Foundation"],
        [4843, "OPC UA TCP Protocol over TLS/SSL for OPC Unified Architecture from OPC Foundation"],
        [4847, "Web Fresh Communication"],
        [4848, "Java"],
        [4894, "LysKOM Protocol A"],
        [4949, "Munin Resource Monitoring Tool"],
        [4950, "Cylon Controls UC32 Communications Port"],
        [5000, "UPnP-Windows network device interoperability"],
        [5000, "VTun"],
        [5000, "Synology Inc. Management Console"],
        [5000, "Flask Development Webserver"],
        [5000, "Heroku console access"],
        [5000, "AT&T U-verse public"],
        [5001, "Slingbox and Slingplayer"],
        [5001, "Synology Inc. Secured Management Console"],
        [5002, "ASSA ARX access control system"],
        [5003, "FileMaker - name binding and transport"],
        [5010, "Registered to: TelePath (the IBM FlowMark workflow-management system messaging platform)"],
        [5011, "TelePath (the IBM FlowMark workflow-management system messaging platform)"],
        [5031, "AVM CAPI-over-TCP (ISDN over Ethernet tunneling)"],
        [5037, "Android ADB server"],
        [5048, "Texai Message Service"],
        [5050, "Yahoo! Messenger"],
        [5051, "ita-agent Symantec Intruder Alert"],
        [5060, "Session Initiation Protocol (SIP)"],
        [5061, "Session Initiation Protocol (SIP) over TLS"],
        [5062, "Localisation access"],
        [5082, "Qpur Communication Protocol"],
        [5083, "Qpur File Protocol"],
        [5084, "EPCglobal Low Level Reader Protocol (LLRP)"],
        [5085, "EPCglobal Low Level Reader Protocol (LLRP) over TLS"],
        [5099, "SafeNet"],
        [5104, "IBM Tivoli Framework NetCOOL/Impact"],
        [5121, "Neverwinter Nights"],
        [5124, "TorgaNET (Micronational Darknet)"],
        [5125, "TorgaNET (Micronational Intelligence Darknet)"],
        [5150, "ATMP Ascend Tunnel Management Protocol"],
        [5151, "ESRI SDE Instance"],
        [5154, "BZFlag"],
        [5172, "PC over IP Endpoint Management"],
        [5190, "AOL Instant Messenger protocol"],
        [5200, "EchoLink VoIP Amateur Radio Software (Information)"],
        [5222, "Extensible Messaging and Presence Protocol (XMPP) client connection"],
        [5223, "Apple Push Notification Service"],
        [5223, "Extensible Messaging and Presence Protocol (XMPP) client connection over SSL"],
        [5228, "HP Virtual Room Service"],
        [5228, "Google Play"],
        [5242, "Viber"],
        [5243, "Viber"],
        [5269, "Extensible Messaging and Presence Protocol (XMPP) server-to-server connection"],
        [5280, "Extensible Messaging and Presence Protocol (XMPP)"],
        [5281, "Undo License Manager"],
        [5281, "Extensible Messaging and Presence Protocol (XMPP)"],
        [5298, "Extensible Messaging and Presence Protocol (XMPP)"],
        [5349, "STUN Behavior Discovery over TLS."],
        [5355, "Link-Local Multicast Name Resolution (LLMNR)"],
        [5357, "Web Services for Devices (WSDAPI) (only provided by Windows Vista"],
        [5358, "WSDAPI Applications to Use a Secure Channel (only provided by Windows Vista"],
        [5402, "Multicast File Transfer Protocol (MFTP)"],
        [5405, "NetSupport Manager"],
        [5412, "IBM Rational Synergy (Telelogic Synergy) (Continuus CM) Message Router"],
        [5413, "Wonderware SuiteLink service"],
        [5417, "SNS Agent"],
        [5421, "NetSupport Manager"],
        [5432, "PostgreSQL"],
        [5433, "Bouwsoft file/webserver"],
        [5480, "VMware VAMI (Virtual Appliance Management Infrastructure)"],
        [5481, "Schneider Electric's ClearSCADA (SCADA implementation for Windows)"],
        [5495, "IBM Cognos TM1 Admin server"],
        [5498, "Hotline tracker server connection"],
        [5500, "Hotline control connection"],
        [5500, "VNC Remote Frame Buffer RFB protocol-for incoming listening viewer"],
        [5501, "Hotline file transfer connection"],
        [5517, "Setiqueue Proxy server client for SETI@Home project"],
        [5550, "Hewlett-Packard Data Protector"],
        [5554, "Fastboot default wireless port"],
        [5555, "Oracle WebCenter Content: Inbound Refinery-Intradoc"],
        [5555, "Freeciv versions up to 2.0"],
        [5556, "Freeciv"],
        [5568, "Session Data Transport (SDT)"],
        [5631, "pcANYWHEREdata"],
        [5656, "IBM Lotus Sametime p2p file transfer"],
        [5666, "NRPE (Nagios)"],
        [5667, "NSCA (Nagios)"],
        [5670, "FILEMQ ZeroMQ File Message Queuing Protocol"],
        [5672, "AMQP"],
        [5701, "Hazelcast default communication port"],
        [5722, "Microsoft RPC"],
        [5718, "Microsoft DPM Data Channel (with the agent coordinator)"],
        [5719, "Microsoft DPM Data Channel (with the protection agent)"],
        [5723, "System Center Operations Manager"],
        [5724, "Operations Manager Console"],
        [5741, "IDA Discover Port 1"],
        [5742, "IDA Discover Port 2"],
        [5800, "VNC Remote Frame Buffer RFB protocol over HTTP / ProjectWise Server"],
        [5900, "VNC Remote Frame Buffer RFB protocol"],
        [5931, "AMMYY admin Remote Control"],
        [5938, "TeamViewer remote desktop protocol"],
        [5984, "CouchDB database server"],
        [5985, "Windows PowerShell Default psSession Port"],
        [5986, "Windows PowerShell Default psSession Port"],
        [5988, "CIM-XML (DMTF Protocol)"],
        [5989, "CIM-XML (DMTF Protocol)"],
        [6000, "X11-used between an X client and server over the network"],
        [6005, "Default for BMC Software Control-M/Server-Socket"],
        [6005, "Default for Camfrog chat & cam client"],
        [6009, "JD Edwards EnterpriseOne ERP system JDENet messaging client listener"],
        [6050, "Arcserve backup"],
        [6051, "Arcserve backup"],
        [6086, "Peer Distributed Transfer Protocol (PDTP)"],
        [6100, "Vizrt System"],
        [6100, "Ventrilo authentication for version 3"],
        [6101, "Backup Exec Agent Browser"],
        [6110, "softcm"],
        [6111, "spc"],
        [6112, "dtspcd"],
        [6112, "Blizzard's Battle.net gaming service and some games"],
        [6112, "Club Penguin Disney online game for kids"],
        [6113, "Club Penguin Disney online game for kids"],
        [6136, "ObjectDB database server"],
        [6159, "ARINC 840 EFB Application Control Interface"],
        [6200, "Oracle WebCenter Content Portable: Content Server (With Native UI) and Inbound Refinery"],
        [6201, "Oracle WebCenter Content Portable: Admin"],
        [6225, "Oracle WebCenter Content Portable: Content Server Web UI"],
        [6227, "Oracle WebCenter Content Portable: JavaDB"],
        [6240, "Oracle WebCenter Content Portable: Capture"],
        [6244, "Oracle WebCenter Content Portable: Content Server-Intradoc Socket port"],
        [6255, "Oracle WebCenter Content Portable: Inbound Refinery-Intradoc Socket port"],
        [6260, "planet M.U.L.E."],
        [6262, "Sybase Advantage Database Server"],
        [6346, "gnutella-svc"],
        [6347, "gnutella-rtr"],
        [6350, "App Discovery and Access Protocol"],
        [6379, "Redis key-value data store"],
        [6389, "EMC CLARiiON"],
        [6432, "PgBouncer-A connection pooler for PostgreSQL"],
        [6436, "Leap Motion Websocket Server TLS"],
        [6437, "Leap Motion Websocket Server"],
        [6444, "Sun Grid Engine Qmaster Service"],
        [6445, "Sun Grid Engine Execution Service"],
        [6502, "Netop Remote Control"],
        [6513, "NETCONF over TLS"],
        [6514, "Syslog over TLS"],
        [6515, "Elipse RPC Protocol (REC)"],
        [6522, "Gobby (and other libobby-based software)"],
        [6523, "Gobby 0.5 (and other libinfinity-based software)"],
        [6543, "Pylons project#Pyramid Default Pylons Pyramid web service port"],
        [6556, "Check MK Agent"],
        [6566, "SANE (Scanner Access Now Easy)-SANE network scanner daemon"],
        [6560, "Speech-Dispatcher daemon"],
        [6561, "Speech-Dispatcher daemon"],
        [6600, "Microsoft Hyper-V Live"],
        [6600, "Music Player Daemon (MPD)"],
        [6601, "Microsoft Forefront Threat Management Gateway"],
        [6602, "Microsoft Windows WSS Communication"],
        [6619, "odette-ftps"],
        [6622, "Multicast FTP"],
        [6653, "OpenFlow"],
        [6660, "Internet Relay Chat (IRC)"],
        [6661, "Internet Relay Chat (IRC)"],
        [6662, "Internet Relay Chat (IRC)"],
        [6663, "Internet Relay Chat (IRC)"],
        [6664, "Internet Relay Chat (IRC)"],
        [6665, "Internet Relay Chat (IRC)"],
        [6666, "Internet Relay Chat (IRC)"],
        [6667, "Internet Relay Chat (IRC)"],
        [6668, "Internet Relay Chat (IRC)"],
        [6669, "Internet Relay Chat (IRC)"],
        [6679, "Osorno Automation Protocol (OSAUT)"],
        [6679, "IRC SSL (Secure Internet Relay Chat)-often used"],
        [6690, "Synology Cloud station"],
        [6697, "IRC SSL (Secure Internet Relay Chat)-often used"],
        [6699, "WinMX (see also 6257)"],
        [6715, "AberMUD and derivatives default port"],
        [6783, "Splashtop Remote server broadcast"],
        [6784, "Splashtop Remote server broadcast"],
        [6785, "Splashtop Remote server broadcast"],
        [6789, "Campbell Scientific Loggernet Software / Bucky's Instant Messaging Program"],
        [6869, "Derandom default server"],
        [6881, "BitTorrent part of full range of ports used most often"],
        [6882, "BitTorrent part of full range of ports used most often"],
        [6883, "BitTorrent part of full range of ports used most often"],
        [6884, "BitTorrent part of full range of ports used most often"],
        [6885, "BitTorrent part of full range of ports used most often"],
        [6886, "BitTorrent part of full range of ports used most often"],
        [6887, "BitTorrent part of full range of ports used most often"],
        [6888, "BitTorrent part of full range of ports used most often / MUSE"],
        [6889, "BitTorrent part of full range of ports used most often"],
        [6890, "BitTorrent part of full range of ports used most often"],
        [6891, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6892, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6893, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6894, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6895, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6896, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6897, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6898, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6899, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6900, "BitTorrent part of full range of ports used most often / Windows Live Messenger File transfer"],
        [6901, "Windows Live Messenger (Voice)"],
        [6969, "acmsoda"],
        [6969, "BitTorrent tracker"],
        [7000, "Default for Vuze's built in HTTPS Bittorrent Tracker"],
        [7000, "Avira Server Management Console"],
        [7001, "Avira Server Management Console"],
        [7001, "Default for BEA WebLogic Server's HTTP server"],
        [7002, "Default for BEA WebLogic Server's HTTPS server"],
        [7005, "Default for BMC Software Control-M/Server and Control-M/Agent for Agent-to-Server"],
        [7006, "Default for BMC Software Control-M/Server and Control-M/Agent for Server-to-Agent"],
        [7010, "Default for Cisco AON AMC (AON Management Console)"],
        [7022, "Database mirroring endpoints"],
        [7025, "Zimbra LMTP"],
        [7047, "Zimbra conversion server"],
        [7133, "Enemy Territory: Quake Wars"],
        [7144, "Peercast"],
        [7145, "Peercast"],
        [7171, "Tibia"],
        [7262, "CNAP (Calypso Network Access Protocol)"],
        [7272, "WatchMe - WatchMe Monitoring"],
        [7306, "Zimbra mysql"],
        [7307, "Zimbra mysql"],
        [7396, "Web control interface for Folding@home v7.3.6 and later"],
        [7400, "RTPS (Real Time Publish Subscribe) DDS Discovery"],
        [7401, "RTPS (Real Time Publish Subscribe) DDS User-Traffic"],
        [7402, "RTPS (Real Time Publish Subscribe) DDS Meta-Traffic"],
        [7471, "Stateless Transport Tunneling (STT)"],
        [7473, "Rise: The Vieneo Province"],
        [7474, "Neo4J Server webadmin"],
        [7478, "Default port used by Open iT Server."],
        [7542, "Saratoga file transfer protocol"],
        [7547, "CPE WAN Management Protocol (CWMP) Technical Report 069"],
        [7624, "Instrument Neutral Distributed Interface"],
        [7631, "ERLPhase"],
        [7634, "hddtemp-Utility to monitor hard drive temperature"],
        [7652, "I2P anonymizing overlay network"],
        [7653, "I2P anonymizing overlay network"],
        [7654, "I2P anonymizing overlay network"],
        [7655, "I2P anonymizing overlay network"],
        [7656, "I2P anonymizing overlay network"],
        [7657, "I2P anonymizing overlay network"],
        [7658, "I2P anonymizing overlay network"],
        [7659, "I2P anonymizing overlay network"],
        [7660, "I2P anonymizing overlay network"],
        [7670, "BrettspielWelt BSW Boardgame Portal"],
        [7687, "Bolt database connection"],
        [7777, "iChat server file transfer proxy"],
        [7777, "Oracle Cluster File System 2"],
        [7777, "Windows backdoor program tini.exe default"],
        [7777, "Just Cause 2: Multiplayer Mod Server"],
        [7777, "Terraria default server"],
        [7831, "Default used by Smartlaunch Internet Cafe Administration"],
        [7880, "PowerSchool Gradebook Server"],
        [7890, "Default that will be used by the iControl Internet Cafe Suite Administration software"],
        [7915, "Default for YSFlight server"],
        [7935, "Fixed port used for Adobe Flash Debug Player to communicate with a debugger (Flash IDE"],
        [7990, "Atlassian Bitbucket (default port)"],
        [8000, "Commonly used for Internet radio streams such as SHOUTcast"],
        [8005, "Tomcat remote shutdown"],
        [8006, "Quest AppAssure 5 API"],
        [8007, "Quest AppAssure 5 Engine"],
        [8008, "Alternative port for HTTP. See also ports 80 and 8080."],
        [8008, "IBM HTTP Server administration default"],
        [8008, "iCal"],
        [8009, "Apache JServ Protocol (ajp13)"],
        [8069, "OpenERP 5.0 XML-RPC protocol"],
        [8070, "OpenERP 5.0 NET-RPC protocol"],
        [8074, "Gadu-Gadu"],
        [8075, "Killing Floor web administration interface"],
        [8080, "Alternative port for HTTP. See also ports 80 and 8008."],
        [8080, "Apache Tomcat"],
        [8080, "Atlassian JIRA applications"],
        [8088, "Asterisk management access via HTTP"],
        [8089, "Fritz!Box automatic TR-069 configuration"],
        [8090, "Coral Content Distribution Network (legacy; 80 and 8080 now supported)"],
        [8111, "JOSM Remote Control"],
        [8112, "PAC Pacifica Coin"],
        [8118, "Privoxy-advertisement-filtering Web proxy"],
        [8123, "Polipo Web proxy"],
        [8139, "Puppet (software) Client agent"],
        [8140, "Puppet (software) Master server"],
        [8172, "Microsoft Remote Administration for IIS Manager"],
        [8184, "NCSA Brown Dog Data Access Proxy"],
        [8194, "Bloomberg Application"],
        [8195, "Bloomberg Application"],
        [8200, "GoToMyPC"],
        [8200, "MiniDLNA media server Web Interface"],
        [8243, "HTTPS listener for Apache Synapse"],
        [8245, "Dynamic DNS for at least No-IP and DyDNS"],
        [8280, "HTTP listener for Apache Synapse"],
        [8281, "HTTP Listener for Gatecraft Plugin"],
        [8291, "Winbox-Default on a MikroTik RouterOS for a Windows application used to administer MikroTik RouterOS"],
        [8332, "Bitcoin JSON-RPC server"],
        [8333, "Bitcoin"],
        [8337, "VisualSVN Distributed File System Service (VDFS)"],
        [8384, "Syncthing web GUI"],
        [8388, "Shadowsocks proxy server"],
        [8443, "SW Soft Plesk Control Panel"],
        [8443, "Apache Tomcat SSL"],
        [8443, "Promise WebPAM SSL"],
        [8443, "iCal over SSL"],
        [8444, "Bitmessage"],
        [8484, "MapleStory Login Server"],
        [8500, "Adobe ColdFusion built-in web server"],
        [8629, "Tibero database"],
        [8642, "Lotus Notes Traveler auto synchronization for Windows Mobile and Nokia devices"],
        [8691, "Ultra Fractal"],
        [8880, "Alternate port of CDDB (Compact Disc Database) protocol"],
        [8883, "Secure MQTT (MQTT over TLS)"],
        [9000, "SonarQube Web Server"],
        [9000, "DBGp"],
        [9000, "SqueezeCenter web server & streaming"],
        [9000, "Play! Framework web server"],
        [9000, "Hadoop NameNode default port"],
        [9000, "PHP-FPM default port"],
        [9000, "QBittorrent's embedded torrent tracker default port"],
        [9001, "ETL Service Manager"],
        [9001, "DBGp Proxy"],
        [9001, "HSQLDB default port"],
        [9006, "Tomcat in standalone mode"],
        [9030, "Tor often used"],
        [9042, "Apache Cassandra native protocol clients"],
        [9043, "WebSphere Application Server Administration Console secure"],
        [9050, "Tor"],
        [9051, "Tor"],
        [9060, "WebSphere Application Server Administration Console"],
        [9080, "glrpc"],
        [9080, "WebSphere Application Server HTTP Transport (port 1) default"],
        [9080, "Remote Potato by FatAttitude"],
        [9080, "ServerWMC"],
        [9090, "Openfire Administration Console"],
        [9090, "SqueezeCenter control (CLI)"],
        [9090, "Cherokee Admin Panel"],
        [9091, "Openfire Administration Console (SSL Secured)"],
        [9091, "Transmission (BitTorrent client) Web Interface"],
        [9092, "H2 (DBMS) Database Server"],
        [9092, "Apache Kafka A Distributed Streaming Platform"],
        [9100, "PDL Data Stream"],
        [9101, "Bacula Director"],
        [9102, "Bacula File Daemon"],
        [9103, "Bacula Storage Daemon"],
        [9119, "MXit Instant Messenger"],
        [9150, "Tor"],
        [9191, "Sierra Wireless Airlink"],
        [9199, "Avtex LLC-qStats"],
        [9200, "Elasticsearch"],
        [9217, "iPass Platform Service"],
        [9293, "Sony PlayStation RemotePlay"],
        [9300, "IBM Cognos BI"],
        [9306, "Sphinx Native API"],
        [9309, "Sony PlayStation Vita Host Collaboration WiFi Data Transfer"],
        [9312, "Sphinx SphinxQL"],
        [9332, "Litecoin JSON-RPC server"],
        [9333, "Litecoin"],
        [9339, "Clash of Clans"],
        [9389, "adws"],
        [9418, "git"],
        [9419, "MooseFS distributed file system - master control port"],
        [9420, "MooseFS distributed file system - master command port"],
        [9421, "MooseFS distributed file system - master client port"],
        [9422, "MooseFS distributed file system - Chunkservers"],
        [9425, "MooseFS distributed file system - CGI server"],
        [9443, "VMware Websense Triton console "],
        [9443, "NCSA Brown Dog Data Tilling Service"],
        [9535, "mngsuite"],
        [9536, "laes-bf"],
        [9675, "Spiceworks Desktop"],
        [9676, "Spiceworks Desktop"],
        [9785, "Viber"],
        [9800, "WebDAV Source"],
        [9875, "Club Penguin Disney online game for kids"],
        [9898, "Tripwire-File Integrity Monitoring Software"],
        [9981, "TVHeadend HTTP server (web interface)"],
        [9982, "TVHeadend HTSP server (Streaming protocol)"],
        [9997, "Splunk port for communication between the forwarders and indexers"],
        [10000, "Network Data Management Protocol"],
        [10009, "CrossFire"],
        [10010, "Open Object Rexx (ooRexx) rxapi daemon"],
        [10024, "Zimbra smtp "],
        [10025, "Zimbra smtp "],
        [10042, "Mathoid server"],
        [10050, "Zabbix agent"],
        [10051, "Zabbix trapper"],
        [10080, "Touhou fight games (Immaterial and Missing Power"],
        [10172, "Intuit Quickbooks client"],
        [10200, "FRISK Software International's f-protd virus scanning daemon for Unix platforms"],
        [10201, "FRISK Software International's f-protd virus scanning daemon for Unix platforms"],
        [10202, "FRISK Software International's f-protd virus scanning daemon for Unix platforms"],
        [10203, "FRISK Software International's f-protd virus scanning daemon for Unix platforms"],
        [10204, "FRISK Software International's f-protd virus scanning daemon for Unix platforms"],
        [10212, "GE Intelligent Platforms Proficy HMI/SCADA - CIMPLICITY WebView"],
        [10514, "TLS-enabled Rsyslog (default by convention)"],
        [10891, "Jungle Disk (this port is opened by the Jungle Disk Monitor service on the localhost)"],
        [10933, "Listen port used by the Octopus Deploy Tentacle deployment agent"],
        [11001, "metasys ( Johnson Controls Metasys java AC control environment )"],
        [11111, "RiCcI"],
        [11112, "ACR/NEMA Digital Imaging and Communications in Medicine (DICOM)"],
        [11211, "memcached"],
        [11214, "memcached incoming SSL proxy"],
        [11215, "memcached internal outgoing SSL proxy"],
        [11311, "Robot Operating System master"],
        [11371, "OpenPGP HTTP key server"],
        [11753, "OpenRCT2 multiplayer"],
        [12013, "Audition Online Dance Battle"],
        [12043, "Second Life"],
        [12046, "Second Life"],
        [12345, "Cube World"],
        [12345, "Little Fighter 2"],
        [12443, "IBM HMC web browser management access over HTTPS instead of default port 443"],
        [12489, "NSClient/NSClient++/NC_Net (Nagios)"],
        [12975, "LogMeIn Hamachi"],
        [13008, "CrossFire"],
        [13075, "Default"],
        [13720, "Symantec NetBackup-bprd (formerly VERITAS)"],
        [13721, "Symantec NetBackup-bpdbm (formerly VERITAS)"],
        [13724, "Symantec Network Utility-vnetd (formerly VERITAS)"],
        [13782, "Symantec NetBackup-bpcd (formerly VERITAS)"],
        [13783, "Symantec VOPIED protocol (formerly VERITAS)"],
        [13785, "Symantec NetBackup Database-nbdb (formerly VERITAS)"],
        [13786, "Symantec nomdb (formerly VERITAS)"],
        [15000, "psyBNC"],
        [15000, "Wesnoth"],
        [15000, "Kaspersky Network Agent"],
        [15345, "XPilot Contact"],
        [16000, "Oracle WebCenter Content: Imaging"],
        [16000, "shroudBNC"],
        [16080, "Mac OS X Server Web (HTTP) service with performance cache"],
        [16200, "Oracle WebCenter Content: Content Server"],
        [16225, "Oracle WebCenter Content: Content Server Web UI"],
        [16250, "Oracle WebCenter Content: Inbound Refinery"],
        [16261, "Project Zomboid multiplayer"],
        [16300, "Oracle WebCenter Content: Records Management"],
        [16400, "Oracle WebCenter Content: Capture"],
        [17011, "Worms multiplayer"],
        [17500, "Dropbox LanSync Protocol (db-lsp)"],
        [18091, "memcached Internal REST HTTPS for SSL"],
        [18092, "memcached Internal CAPI HTTPS for SSL"],
        [18104, "RAD PDF Service"],
        [18200, "Audition Online Dance Battle"],
        [18201, "Audition Online Dance Battle"],
        [18206, "Audition Online Dance Battle"],
        [18300, "Audition Online Dance Battle"],
        [18301, "Audition Online Dance Battle"],
        [18306, "Audition Online Dance Battle"],
        [18333, "Bitcoin testnet"],
        [18400, "Audition Online Dance Battle"],
        [18401, "Audition Online Dance Battle"],
        [18505, "Audition Online Dance Battle R4p3 Server"],
        [18506, "Audition Online Dance Battle"],
        [18605, "X-BEAT status/version check"],
        [18606, "X-BEAT"],
        [19000, "Audition Online Dance Battle"],
        [19001, "Audition Online Dance Battle"],
        [19150, "Gkrellm Server"],
        [19226, "Panda Software AdminSecure Communication Agent"],
        [19283, "K2-KeyAuditor & KeyServer"],
        [19294, "Google Talk Voice and Video connections"],
        [19315, "KeyShadow for K2-KeyAuditor & KeyServer"],
        [19813, "4D database Client Server Communication"],
        [19814, "4D database DB4D Communication"],
        [20560, "Killing Floor"],
        [21025, "Starbound Server (default)"],
        [22000, "Syncthing (default)"],
        [22136, "FLIR Systems Camera Resource Protocol"],
        [22222, "Davis Instruments"],
        [24441, "Pyzor spam detection network"],
        [24465, "Tonido Directory Server for Tonido which is a Personal Web App and P2P platform"],
        [24554, "BINKP"],
        [25565, "Minecraft multiplayer server"],
        [26000, "id Software's Quake server / EVE Online"],
        [26900, "EVE Online"],
        [26901, "EVE Online"],
        [27000, "PowerBuilder SySAM license server / FlexNet Publisher's License server"],
        [27001, "FlexNet Publisher's License server"],
        [27002, "FlexNet Publisher's License server"],
        [27003, "FlexNet Publisher's License server"],
        [27004, "FlexNet Publisher's License server"],
        [27005, "FlexNet Publisher's License server"],
        [27006, "FlexNet Publisher's License server"],
        [27007, "FlexNet Publisher's License server"],
        [27008, "FlexNet Publisher's License server"],
        [27009, "FlexNet Publisher's License server"],
        [28852, "Killing Floor"],
        [28910, "Nintendo Wi-Fi Connection"],
        [28960, "Call of Duty; Call of Duty: United Offensive; Call of Duty 2; Call of Duty 4: Modern Warfare;"],
        [29070, "Jedi Knight: Jedi Academy by Ravensoft"],
        [29900, "Nintendo Wi-Fi Connection"],
        [29901, "Nintendo Wi-Fi Connection"],
        [29920, "Nintendo Wi-Fi Connection"],
        [30564, "Multiplicity: keyboard/mouse/clipboard sharing software"],
        [31337, "Back Orifice remote administration tool"],
        [31438, "Rocket U2"],
        [31457, "TetriNET"],
        [32400, "Plex Media Server"],
        [32764, "A backdoor found on certain Linksys"],
        [32887, "Ace of Spades"],
        [32976, "LogMeIn Hamachi"],
        [33434, "traceroute"],
        [35357, "OpenStack Identity (Keystone) administration"],
        [40000, "SafetyNET p - a real-time Industrial Ethernet protocol"],
        [43110, "ZeroNet web UI default port"],
        [44405, "Mu Online Connect Server"],
        [44818, "EtherNet/IP explicit messaging"],
        [47001, "Windows Remote Management Service (WinRM)"],
        [47808, "BACnet Building Automation and Control Networks (4780810 = BAC016)"]
    ]

    netbiosCodes = [
        #[code, description]
        ["00U", "Workstation Service"],
        ["01U", "Messenger Service"],
        ["01G", "Master Browser"],
        ["03U", "Messenger Service"],
        ["06U", "RAS Server Service"],
        ["1FU", "NetDDE Service"],
        ["20U", "File Server Service"],
        ["21U", "RAS Client Service"],
        ["22U", "Microsoft Exchange Interchange(MSMail Connector)"],
        ["23U", "Microsoft Exchange Store"],
        ["24U", "Microsoft Exchange Directory"],
        ["30U", "Modem Sharing Server Service"],
        ["31U", "Modem Sharing Client Service"],
        ["43U", "SMS Clients Remote Control"],
        ["44U", "SMS Administrators Remote Control Tool"],
        ["45U", "SMS Clients Remote Chat"],
        ["46U", "SMS Clients Remote Transfer"],
        ["4CU", "DEC Pathworks TCPIP service on Windows NT"],
        ["42U", "mccaffee anti-virus"],
        ["52U", "DEC Pathworks TCPIP service on Windows NT"],
        ["87U", "Microsoft Exchange MTA"],
        ["6AU", "Microsoft Exchange IMC"],
        ["BEU", "Network Monitor Agent"],
        ["BFU", "Network Monitor Application"],
        ["03U", "Messenger Service"],
        ["00G", "Domain Name"],
        ["1BU", "Domain Master Browser"],
        ["1CG", "Domain Controllers"],
        ["1DU", "Master Browser"],
        ["1EG", "Browser Service Elections"],
        ["1CG", "IIS"],
        ["00U", "IIS"]
    ]